"""Agent identity generation — Ed25519 keypair + ``ag_`` prefixed ID."""

from __future__ import annotations

import base64
import uuid
from dataclasses import asdict, dataclass

from nacl.signing import SigningKey

__all__ = ["AgentIdentity", "generate_agent_identity"]


@dataclass(frozen=True)
class AgentIdentity:
    """A fresh MandateZ agent identity.

    ``private_key`` is returned in hex by default — that's what ships
    with :func:`generate_agent_identity`. The signing module accepts
    hex, base64, 32-byte seeds, and 64-byte libsodium secret keys, so
    you can interop freely with keys generated by ``@mandatez/sdk``.
    """

    agent_id: str
    public_key: str  # base64, 32 bytes
    private_key: str  # hex, 32-byte seed

    def as_dict(self) -> dict:
        return asdict(self)


def generate_agent_identity() -> AgentIdentity:
    """Generate a brand-new agent identity.

    The private key is a 32-byte Ed25519 seed encoded as hex. The
    public key is base64-encoded so that AgentEvents produced by this
    SDK interoperate directly with events produced by the TypeScript
    SDK (which always emits base64 public keys).
    """
    signing_key = SigningKey.generate()
    seed = bytes(signing_key)
    verify_key_bytes = bytes(signing_key.verify_key)

    return AgentIdentity(
        agent_id=f"ag_{uuid.uuid4().hex[:12]}",
        private_key=seed.hex(),
        public_key=base64.b64encode(verify_key_bytes).decode("ascii"),
    )
